language: c
compiler:
  - clang
  - gcc
before_install:
  - if [ "$CC" = "clang" ]; then export CXX="clang++"; else export CXX="g++"; fi
  - if [ "$EXTRA_CFLAGS" = "-DUSE_VALGRIND" ]; then sudo add-apt-repository -y ppa:tmsz-kapela/valgrind-pmem; fi
  - sudo apt-get update -qq
  - sudo apt-get install -y libunwind7-dev autoconf devscripts pkg-config
  - if [ "$EXTRA_CFLAGS" = "-DUSE_VALGRIND" ]; then sudo apt-get install -y valgrind; fi
  - echo "NON_PMEM_FS_DIR=/tmp" > src/test/testconfig.sh
  - echo "PMEM_FS_DIR=/tmp" >> src/test/testconfig.sh
  - echo "PMEM_FS_DIR_FORCE_PMEM=1" >> src/test/testconfig.sh
  - sudo mount -t tmpfs none /tmp -osize=4G
script:
  - which clang-format
  - clang-format --version
  - ls /usr/local/clang
  - sudo apt-cache search clang-format
  - clang-format --version
