sudo: false
addons:
    apt:
        packages:
        - uuid-dev
        - libc6-dbg
        - autoconf
cache:
    directories:
        - $HOME/valgrind
language: c
compiler:
  - clang
  - gcc
before_install:
  - bash install-valgrind.sh
  - cp src/test/testconfig.sh.example src/test/testconfig.sh
  - export PATH=$PATH:$HOME/valgrind/bin
  - export C_INCLUDE_PATH=$C_INCLUDE_PATH:$HOME/valgrind/include
script: make cstyle && make -j2 && make -j2 test && make check && make DESTDIR=/tmp source
env:
  - EXTRA_CFLAGS=-DUSE_VALGRIND
  - EXTRA_CFLAGS=

