#!/bin/bash -e
#
# Copyright (c) 2014-2015, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of Intel Corporation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# src/test/blk_rw_reorder/TEST0 -- reordering enabled unit test for pmemblk
#
export UNITTEST_NAME=blk_rw_reorder/TEST0
export UNITTEST_NUM=0
# standard unit test setup
. ../unittest/unittest.sh

# doesn't make sense to run in local directory
require_fs_type pmem non-pmem
require_build_type debug

setup

# single arena and minimum pmemblk pool file case
MIN_POOL_SIZE=$((16*1024*1024 + 8*1024))
create_blk_pool $DIR/testfile1 $MIN_POOL_SIZE 512

OPS="./blk_rw_reorder$EXESUFFIX 512 $DIR/testfile1 o w:0 w:1 w:3 w:8 e:8 z:9"

do_reorder_test $DIR/testfile1 "$OPS" "outfile$UNITTEST_NUM.log" prog $PMEMPOOL\
	"check -qry"

expect_normal_exit ./blk_rw_reorder$EXESUFFIX 512 $DIR/testfile1 o r:0 r:1 r:3

check

pass
